version: '3'

services:
  api:
    build: ./containers/api
    volumes:
      - .:/code
    depends_on:
      - mongo
    ports:
      - 3000:3000
    command: ["/code/run-dev.sh"]

  mongo:
    image: mongo:4.2-bionic
