services:
  my_command:
    class: MyCommand
    kwargs:
      input: '@console_input'
      output: '@console_output'
    tag:
      - command

  home_controller:
    class: HomeController
    tag:
      - controller
