services:
  app.my_command:
    class: App::MyCommand
    kwargs:
      input: '@console_input'
      output: '@console_output'
    tag:
      - command

  # framework extensions
  http.error_handler:
   class: App::ErrorHandler

  # controllers
  app.home_controller:
    class: App::HomeController
    kwargs:
      i18n: '@i18n.translator'
    tag:
      - http.controller

  app.oauth_controller:
    class: App::OAuthController
    kwargs:
      auth_service: '@app.auth_service'
    tag:
      - http.controller

  app.user_controller:
    class: App::UserController
    kwargs:
      user_serializer: '@app.user_serializer'
      user_service: '@app.user_service'
      user_repository: '@app.user_repository'
    tag:
      - http.controller

  # services
  app.cors_service:
    class: App::CorsService
  
  app.user_service:
    class: App::UserService
    kwargs:
      user_repository: '@app.user_repository'
      crypt_service: '@app.crypt_service'
      i18n: '@i18n.translator'

  app.auth_service:
    class: App::AuthService
    kwargs:
      user_repository: '@app.user_repository'
      crypt_service: '@app.crypt_service'
      app_secret: '%app_secret:String%'
      i18n: '@i18n.translator'

  app.crypt_service:
    class: App::CryptService
    kwargs:
      app_secret: '%app_secret:String%'

  # repositories
  app.user_repository:
    class: App::UserRepository
    kwargs:
      connection: '@db.connection'

  # serializers
  app.user_serializer:
    class: App::UserSerializer

  # middlewares
  app.cors_middleware:
    class: App::CorsMiddleware
    kwargs:
      cors_service: '@app.cors_service'
    tag:
      - http.middleware

  app.content_type_middleware:
    class: App::ContentTypeMiddleware
    tag:
      - http.middleware

  app.accept_language_middleware:
    class: App::AcceptLanguageMiddleware
    tag:
      - http.middleware
    kwargs:
      yaml_data: '@i18n.yaml_data'
      i18n_builder: '@i18n.translator_builder'

  app.auth_middleware:
    class: App::AuthMiddleware
    kwargs:
      auth_service: '@app.auth_service'
    tag:
      - http.middleware
